### ISSUE TITLE
Release binaries and container image

### ISSUE THREAD

**Issue by aarnaud** [MicahParks/jwkset#17]
Can we add a binary and container image build ?

I can propose a PR that use Github Action and gcr.io .

Something like https://github.com/aarnaud/vault-pki-exporter/releases and https://github.com/aarnaud/vault-pki-exporter/pkgs/container/vault-pki-exporter

Have a good day.

**Comment by MicahParks** [comment]
I believe you are interested in a a binary and container image for the `cmd/jwksetinfer` tool.

At this time, I don't know if there is enough demand for this tool for me to build and publish binaries and container images. However, I will leave this issue open. If there are enough people responding with emojis showing a need, I'll likely publish binaries and container images.

I did put together a `Dockerfile` for you. You can find it below. Also, if the Golang toolchain is installed, the `jwksetinfer` tool can be installed with the below command:

```
go install github.com/MicahParks/jwkset/cmd/jwksetinfer@latest
```

```
FROM golang:1 AS builder
RUN cd / && git clone https://github.com/MicahParks/jwkset.git
WORKDIR /jwkset
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags "-s -w" -o jwksetinfer -trimpath cmd/jwksetinfer/*.go

FROM alpine
COPY --from=builder /jwkset/jwksetinfer /jwksetinfer
CMD ["/jwksetinfer"]
```

**Comment by MicahParks** [comment]
I'm going to close this issue for now. If there's wider interest in having the `jwksetinfer` tool as an official public Docker image, please do voice that interest in this issue :+1:
