### ISSUE TITLE
Question about the JWKS Refresh Rate Limiting

### ISSUE THREAD

**Issue by sc-tomer** [MicahParks/jwkset#29]
The current implementation, from my understanding,
uses a rate limiter (RefreshUnknownKID) to control the frequency of JWKS refreshes for unknown KIDs.
My concern is that this may lead to redundant fetches if multiple requests with unknown KIDs arrive within the rate limiting window (e.g. 10 seconds).
Additionally, the last requests to arrive may experience long delays as they will have to wait for the rate limiting delay for each preceding request (if burst is set to 1 for example).

I wonder if we could optimize this, by adding a lock for the fetching process so that only the first request to arrive will initiate the JWKS refresh. Subsequent requests with unknown KIDs would wait for the refresh to complete. After the refresh is complete, the waiting requests will check the local storage for the KID and if the KID is still not found in the local storage, return a "not found" error instead of triggering another refresh, since we just refreshed the JWKS.

I think that this approach would reduce redundant fetches, improve performance, avoid unnecessary refreshes for KIDs that are not present in the JWKS after a fresh refresh, and prevent long delays for the last requests to arrive.

**Comment by MicahParks** [comment]
Thank you @sc-tomer for opening this issue.

I think that the proposed would add too much complexity to the code base for the benefit it provides.

Please note the [behavior of the rate limiter](https://pkg.go.dev/golang.org/x/time/rate#Limiter.WaitN):
> It returns an error if n exceeds the Limiter's burst size, the Context is canceled, or the expected wait time exceeds the Context's Deadline.

To address the concern of long delays for a large queue of JWTs with unknown KIDs, I would suggest shortening the `context.Context` timeout used when performing JWK Set read operations. If the expected wait time supplied by the `context.Context` is longer than the rate limit, than it should return early. This should prevent most queues from forming.

Additionally, if you have control of the JWK Set and JWT issuer, I would ensure the JWT issuer is not using a newly published JWK until it has been published in the JWK Set for about double the length of your refresh interval.

**Comment by sc-tomer** [comment]
That makes sense. 
Thanks @MicahParks , appreciate your help and work on this plugin!
