### ISSUE TITLE
X5TS256 in marshal does not match X5TS256 in marshalled

### ISSUE THREAD

**Issue by d-g-town** [MicahParks/jwkset#32]
Full error: 
```
ERROR Failed to refresh HTTP JWK Set from remote HTTP resource. error="failed to create JWK from JWK Marshal: failed to validate JSON Web Key: failed to validate JWK: X5TS256 in marshal does not match X5TS256 in marshalled" url=https://api.workos.com/sso/jwks/client_01HTQS3YJN2508ECC9DCQ88DRJ
```

JWKS is as follows:
```
{"keys":[{"alg":"RS256","kty":"RSA","use":"sig","n":"5cuZ4ITu8So894-M2TMaJxvLq9_PQvx5uiLbvKOA_IS_9V_whNvIJlBp7b4TNzYsmzDQnHENvz-mDjed0u53xXTA3R51_JMxHehZu2z_VqMMWfZV6GItVv5Vlo0oUy9icff9zZmM_kxP_qivomvwka_ZABPrcKltTWDmoA7LlzIxt-_EMAkVtKOneursO3_qpqNStFHE1AGLtV4yVU4hThBOdbHM2rAvflJLKTfNQMqOu5-qjEF4SonDqqEhHkTBr7p-AHhtK3knrXY9IzjoWN2jwK-PL6bBxrCyxaBmUFNvYTHq4pHWFFTD4zA2lq6_SxkqyAkgHGrn4gZns67lJw","e":"AQAB","kid":"sso_oidc_key_pair_01HTQS3YDY77KTCF3GH521Y6BP","x5c":["MIICwDCCAaigAwIBAgIUSUlRQaD9UEvHiF99VeUBfkKcZQowDQYJKoZIhvcNAQEFBQAwGjEYMBYGA1UEAxMPYXV0aC53b3Jrb3MuY29tMB4XDTI0MDQwNTE4NDI0M1oXDTI5MDQwNTE4NDI0M1owGjEYMBYGA1UEAxMPYXV0aC53b3Jrb3MuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5cuZ4ITu8So894+M2TMaJxvLq9/PQvx5uiLbvKOA/IS/9V/whNvIJlBp7b4TNzYsmzDQnHENvz+mDjed0u53xXTA3R51/JMxHehZu2z/VqMMWfZV6GItVv5Vlo0oUy9icff9zZmM/kxP/qivomvwka/ZABPrcKltTWDmoA7LlzIxt+/EMAkVtKOneursO3/qpqNStFHE1AGLtV4yVU4hThBOdbHM2rAvflJLKTfNQMqOu5+qjEF4SonDqqEhHkTBr7p+AHhtK3knrXY9IzjoWN2jwK+PL6bBxrCyxaBmUFNvYTHq4pHWFFTD4zA2lq6/SxkqyAkgHGrn4gZns67lJwIDAQABMA0GCSqGSIb3DQEBBQUAA4IBAQC6jiPQc+9tdgZ5kZdrAln21wfjHNvM4Q9/UBKHVIkb6G78jUKMZJ5TyTSM3R7O0EzkuU5a0vUStASiOM7U+n/ptTK251aye3D7H3WHnCdOVJQcV/ocYaiOT3Wphw+/wYYBz/pqKtAYjNEvIX6GWC6TgKfIFFu+l8ulVrxscgh9frpU7Zu5/7Gj7MKYqDcKgw/YfTvO3EIBZlL7HOwlMOLnv+o3pYEWpLkvDYlbvaY9f1rLWi5ZyiuZwErgCgYXdDWR9kQE0DrwF6/nlR6Ps3XkyW8D3BVyutu4Pj2Wyotcp0hfnOEupzY1MBF3t8Ke9D0ARWUd5HcW9jX4izUC0RIr"],"x5t#S256":"ICN4ionaWj70EMmUfyV0CLn2Z9fzdWj_kdz6V5bawic"}]}
```

**Comment by MicahParks** [comment]
Thank you for reporting this bug, @d-g-town. I'll look into it now.

**Comment by MicahParks** [comment]
Are you able to share what service created this JWK Set? Something SSO related, perhaps Okta, or another identity provider?

**Comment by MicahParks** [comment]
The cert looks to be issued by `https://workos.com/`?

**Comment by MicahParks** [comment]
This is happening because this package is computing the SHA 256 sum of the X.509 certificate as `fh0LO78PN52GR_8zRHj_wWYPl7046HwPBVtKFgsHttc` but the thumbprint in the JWK Set is `ICN4ionaWj70EMmUfyV0CLn2Z9fzdWj_kdz6V5bawic`. Either this project is computing the thumbprint wrong or whatever created the given JWK Set is.

I hope it's not this project, but maybe it is. I'm going to remove the bug label for now and investigate more. 

If you need a quick way around this, you can turn off validation when parsing this key.

Do this by setting the `SkipAll` field to `true` in `jwkset.ValidationOptions` https://pkg.go.dev/github.com/MicahParks/jwkset#JWKValidateOptions

**Comment by MicahParks** [comment]
Relevant [RFC 7517 snippet](https://datatracker.ietf.org/doc/html/rfc7517#section-4.9):
> The "x5t#S256" (X.509 certificate SHA-256 thumbprint) parameter is a
   base64url-encoded SHA-256 thumbprint (a.k.a. digest) of the DER
   encoding of an X.509 certificate [[RFC5280](https://datatracker.ietf.org/doc/html/rfc5280)].  Note that certificate
   thumbprints are also sometimes known as certificate fingerprints.
   The key in the certificate MUST match the public key represented by
   other members of the JWK.  Use of this member is OPTIONAL.

I took the certificate and made it into a file `cert.crt`:
```
-----BEGIN CERTIFICATE-----
MIICwDCCAaigAwIBAgIUSUlRQaD9UEvHiF99VeUBfkKcZQowDQYJKoZIhvcNAQEFBQAwGjEYMBYGA1UEAxMPYXV0aC53b3Jrb3MuY29tMB4XDTI0MDQwNTE4NDI0M1oXDTI5MDQwNTE4NDI0M1owGjEYMBYGA1UEAxMPYXV0aC53b3Jrb3MuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5cuZ4ITu8So894+M2TMaJxvLq9/PQvx5uiLbvKOA/IS/9V/whNvIJlBp7b4TNzYsmzDQnHENvz+mDjed0u53xXTA3R51/JMxHehZu2z/VqMMWfZV6GItVv5Vlo0oUy9icff9zZmM/kxP/qivomvwka/ZABPrcKltTWDmoA7LlzIxt+/EMAkVtKOneursO3/qpqNStFHE1AGLtV4yVU4hThBOdbHM2rAvflJLKTfNQMqOu5+qjEF4SonDqqEhHkTBr7p+AHhtK3knrXY9IzjoWN2jwK+PL6bBxrCyxaBmUFNvYTHq4pHWFFTD4zA2lq6/SxkqyAkgHGrn4gZns67lJwIDAQABMA0GCSqGSIb3DQEBBQUAA4IBAQC6jiPQc+9tdgZ5kZdrAln21wfjHNvM4Q9/UBKHVIkb6G78jUKMZJ5TyTSM3R7O0EzkuU5a0vUStASiOM7U+n/ptTK251aye3D7H3WHnCdOVJQcV/ocYaiOT3Wphw+/wYYBz/pqKtAYjNEvIX6GWC6TgKfIFFu+l8ulVrxscgh9frpU7Zu5/7Gj7MKYqDcKgw/YfTvO3EIBZlL7HOwlMOLnv+o3pYEWpLkvDYlbvaY9f1rLWi5ZyiuZwErgCgYXdDWR9kQE0DrwF6/nlR6Ps3XkyW8D3BVyutu4Pj2Wyotcp0hfnOEupzY1MBF3t8Ke9D0ARWUd5HcW9jX4izUC0RIr
-----END CERTIFICATE-----
```

Then I used this OpenSSL command:
```
$ openssl x509 -in thing.crt -noout -fingerprint -sha256
sha256 Fingerprint=7E:1D:0B:3B:BF:0F:37:9D:86:47:FF:33:44:78:FF:C1:66:0F:97:BD:38:E8:7C:0F:05:5B:4A:16:0B:07:B6:D7
```

I ran that fingerprint through this Go program:
```go
package main

import (
	"encoding/base64"
	"encoding/hex"
	"strings"
)

func main() {
	a := "7E:1D:0B:3B:BF:0F:37:9D:86:47:FF:33:44:78:FF:C1:66:0F:97:BD:38:E8:7C:0F:05:5B:4A:16:0B:07:B6:D7"
	a = strings.ReplaceAll(a, ":", "")
	b, err := hex.DecodeString(a)
	if err != nil {
		panic(err)
	}
	println(base64.RawURLEncoding.EncodeToString(b))
}
```

Which ouputs `fh0LO78PN52GR_8zRHj_wWYPl7046HwPBVtKFgsHttc`.

I think that this project is calculating SHA 256 certificate thumbprints the same way as OpenSSL, so I'm going to open a support ticket with WorkOS to point that out. It seems they may have a bug to fix. If my logic is flawed, please do point out any mistakes.

**Comment by d-g-town** [comment]
Hey @MicahParks, thanks for the quick responses!

Is there a way to add the `SkipAll` field if I am using your [keyfunc](https://github.com/MicahParks/keyfunc) package?

**Comment by d-g-town** [comment]
Also, could you link the support ticket you opened with WorkOs, so I can keep tabs on it?

**Comment by MicahParks** [comment]
There's no ticket number. But they responded via email already. I imagine someone will take a look later this week. It's a USA company and today is a USA federal holiday.

That's a good request would you open an issue in the keyfunc project?

**Comment by d-g-town** [comment]
Sounds good, and will do!

**Comment by MicahParks** [comment]
@d-g-town WorkOS responded and said they deployed a fix. Would you test again?

**Comment by MicahParks** [comment]
@aivajoe, thanks for including that in this ticket. It seems you've already identified that this is an issue with Auth0. Would you kindly open a ticket with them and inform them of this issue? If you'd rather I do it, would you include the JWK in this ticket? Please do no post any private key material.

**Comment by MicahParks** [comment]
@aivajoe as of today, it's not possible to turn that validation option off with `keyfunc`. This issue should allow you to make that configuration, but work on that hasn't started yet: https://github.com/MicahParks/keyfunc/issues/126

If you're feeling adventurous, the `keyfunc` project is only [one file](https://github.com/MicahParks/keyfunc/blob/main/keyfunc.go), you could edit it to suit your needs until Auth0 has a fix or the `keyfunc` issue for extra options is complete.
